version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    environment:
      - TZ=America/Phoenix

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - TZ=America/Phoenix
      - GF_SECURITY_ADMIN_PASSWORD=75ELPT7ntGSQfuc

  status_checker:
    build: .
    container_name: status_checker
    user: "1000:1000"
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Phoenix

